// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SobelAlgImage.Infrastructure.Data;

namespace SobelAlgImage.Infrastructure.Data.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20201015124703_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("SobelAlgImage.Models.DataModels.ImageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmountOfThreads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcConvolutionTasks")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceGrey100")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceGrey50")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceGrey80")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceOriginal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImageModels");
                });
#pragma warning restore 612, 618
        }
    }
}
